services:
  postgres:
    image: postgres:16 
    container_name: yrkesco-postgres
    environment:
      POSTGRES_DB: yrkesco_db
      POSTGRES_USER: yrkesco_user
      POSTGRES_PASSWORD: yrkesco_password
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck: # "unhealthy" FIXAD
      test: ["CMD-SHELL", "pg_isready -U yrkesco_user -d yrkesco_db"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s  # LÃ¤ngre postgres tid
    networks:
      - yrkesco-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yrkesco-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yrkesco.se
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - yrkesco-network

volumes:
  postgres_data:

networks:
  yrkesco-network: